// Ajax types
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Task types
export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const EMPTY_CATEGORIES_SUCCESS = 'EMPTY_CATEGORIES_SUCCESS';
export const FILTER_BY_KEY = 'FILTER_BY_KEY';
export const SHOW_ALL = 'SHOW_ALL';

// Category types
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';

// Widget types
export const LOAD_WIDGETS_SUCCESS = 'LOAD_WIDGETS_SUCCESS';
export const CHANGE_WIDGET_ORDER = 'CHANGE_WIDGET_ORDER';